.TH "PICOCOIN" 1 "2017-02-15" "" ""
.SH NAME
picocoin \- open source command line bitcoin spv client written in C
.SH SYNOPSIS
.B picocoin
chain-set
.br
.B picocoin
dns-seeds
.br
.B picocoin
list-settings
.br
.B picocoin
new-address
.br
.B picocoin
wallet-addr
.br
.B picocoin
wallet-info
.br
.SH DESCRIPTION
.PP
picocoin is a bitcoin spv client that runs on the
command line.
.TP
\fB\-f\fR 
specify which number you will use to send a message
.TP
\fB\-t\fR
specify which number you will send a message to
.TP
\fB\-d\fR
message you will send
.TP
\fB\-m\fR
send a message to myself
.TP
\fB\-p\fR
accound password

.SH AUTHOR
Written by Aron Xu <happyaron.xu@gmail.com>.
.RE
.PP

.SH RESOURCES
picocoin home page: https://github.com/jgarzik/picocoin
.RE
.PP

.SH COPYING
Copyright \(co 2012 Jeff Garzik.
License MIT
.PP
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.PP

